FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["PcComponentStore.Api.csproj", "."]
RUN dotnet restore
COPY . .
ENV DOTNET_CLI_TELEMETRY_OPTOUT=1
RUN dotnet build -c Release -o /app/build /m:1

FROM build AS publish
RUN dotnet publish -c Release -o /app/publish /p:UseAppHost=false /m:1

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENV ASPNETCORE_URLS=http://+:8080
ENV ASPNETCORE_ENVIRONMENT=Production
ENTRYPOINT ["dotnet", "PcComponentStore.Api.dll"]
