http://localhost:5285

GET http://localhost:5285/weatherforecast/
Accept: application/json

###

POST http://localhost:5285/api/
Content-Type: application/json

{
    "email": "[EMAIL_ADDRESS]",
    "password": "[PASSWORD]"
}
